//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaCupon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRA
    {
        public COMPRA()
        {
            this.CUPON = new HashSet<CUPON>();
        }
    
        public int id_compra { get; set; }
        public System.DateTime compra_fecha { get; set; }
        public int id_oferta { get; set; }
        public int id_cliente { get; set; }
        public decimal cantidad { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual OFERTA OFERTA { get; set; }
        public virtual ICollection<CUPON> CUPON { get; set; }
    }
}
