//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaCupon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMA_PAGO
    {
        public FORMA_PAGO()
        {
            this.CREDITO = new HashSet<CREDITO>();
        }
    
        public int id_forma_pago { get; set; }
        public string tipo_pago_desc { get; set; }
    
        public virtual ICollection<CREDITO> CREDITO { get; set; }
    }
}
