//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaCupon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONALIDAD
    {
        public FUNCIONALIDAD()
        {
            this.FUNCIONALIDAD_ROL = new HashSet<FUNCIONALIDAD_ROL>();
        }
    
        public int id_funcionalidad { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<FUNCIONALIDAD_ROL> FUNCIONALIDAD_ROL { get; set; }
    }
}
