//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaCupon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUBRO
    {
        public RUBRO()
        {
            this.PROVEEDOR = new HashSet<PROVEEDOR>();
        }
    
        public int id_rubro { get; set; }
        public string nombreDeRubro { get; set; }
    
        public virtual ICollection<PROVEEDOR> PROVEEDOR { get; set; }
    }
}
