//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaCupon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
            this.PROVEEDOR = new HashSet<PROVEEDOR>();
            this.ROL_USUARIO = new HashSet<ROL_USUARIO>();
        }
    
        public int id_usuario { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int intentos_login { get; set; }
        public bool estado { get; set; }
    
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        public virtual ICollection<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual ICollection<ROL_USUARIO> ROL_USUARIO { get; set; }
    }
}
