//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaOfertas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUPON
    {
        public int id_cupon { get; set; }
        public string cupon_codigo { get; set; }
        public System.DateTime cupon_fecha_deconsumo { get; set; }
        public decimal cupon_precio_oferta { get; set; }
        public decimal cupon_precio_lista { get; set; }
        public int id_consumidor { get; set; }
        public bool cupon_estado { get; set; }
        public int id_compra { get; set; }
    
        public virtual CLIENTE_DESTINO CLIENTE_DESTINO { get; set; }
        public virtual COMPRA COMPRA { get; set; }
    }
}
