//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaOfertas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOMICILIO
    {
        public DOMICILIO()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
            this.CLIENTE_DESTINO = new HashSet<CLIENTE_DESTINO>();
            this.PROVEEDOR = new HashSet<PROVEEDOR>();
        }
    
        public int id_domicilio { get; set; }
        public string direc_calle { get; set; }
        public string direc_nro_piso { get; set; }
        public string direc_localidad { get; set; }
        public string codigoPostal { get; set; }
        public string direc_nro_depto { get; set; }
    
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        public virtual ICollection<CLIENTE_DESTINO> CLIENTE_DESTINO { get; set; }
        public virtual ICollection<PROVEEDOR> PROVEEDOR { get; set; }
    }
}
