//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaOfertas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA_PROVEEDOR
    {
        public int id_factura { get; set; }
        public decimal nro_factura { get; set; }
        public decimal importe_fact { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public int id_proveedor { get; set; }
    
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
