//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaOfertas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GD2C2019Entities : DbContext
    {
        public GD2C2019Entities()
            : base("name=GD2C2019Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<CLIENTE_DESTINO> CLIENTE_DESTINO { get; set; }
        public DbSet<COMPRA> COMPRA { get; set; }
        public DbSet<CREDITO> CREDITO { get; set; }
        public DbSet<CUPON> CUPON { get; set; }
        public DbSet<DOMICILIO> DOMICILIO { get; set; }
        public DbSet<FACTURA_PROVEEDOR> FACTURA_PROVEEDOR { get; set; }
        public DbSet<FORMA_PAGO> FORMA_PAGO { get; set; }
        public DbSet<FUNCIONALIDAD> FUNCIONALIDAD { get; set; }
        public DbSet<FUNCIONALIDAD_ROL> FUNCIONALIDAD_ROL { get; set; }
        public DbSet<OFERTA> OFERTA { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public DbSet<ROL> ROL { get; set; }
        public DbSet<ROL_USUARIO> ROL_USUARIO { get; set; }
        public DbSet<RUBRO> RUBRO { get; set; }
        public DbSet<TARJETA> TARJETA { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
    }
}
