//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaOfertas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFERTA
    {
        public OFERTA()
        {
            this.COMPRA = new HashSet<COMPRA>();
        }
    
        public int id_oferta { get; set; }
        public string cod_oferta { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public decimal precio_oferta { get; set; }
        public decimal precio_lista { get; set; }
        public int cantDisponible { get; set; }
        public int cant_max_porCliente { get; set; }
        public int id_proveedor { get; set; }
    
        public virtual ICollection<COMPRA> COMPRA { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
