//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaOfertas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROL
    {
        public ROL()
        {
            this.FUNCIONALIDAD_ROL = new HashSet<FUNCIONALIDAD_ROL>();
            this.ROL_USUARIO = new HashSet<ROL_USUARIO>();
        }
    
        public int id_rol { get; set; }
        public string nombre { get; set; }
        public bool estado { get; set; }
    
        public virtual ICollection<FUNCIONALIDAD_ROL> FUNCIONALIDAD_ROL { get; set; }
        public virtual ICollection<ROL_USUARIO> ROL_USUARIO { get; set; }
    }
}
