//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaOfertas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARJETA
    {
        public TARJETA()
        {
            this.CREDITO = new HashSet<CREDITO>();
        }
    
        public int id_tarjeta { get; set; }
        public string nro_tarjeta { get; set; }
        public string titular_tarjeta { get; set; }
        public string banco_tarjeta { get; set; }
        public string tipo_tarjeta { get; set; }
    
        public virtual ICollection<CREDITO> CREDITO { get; set; }
    }
}
