//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCuponFrbaT_REX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.COMPRA = new HashSet<COMPRA>();
            this.CREDITO = new HashSet<CREDITO>();
        }
    
        public int id_cliente { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public decimal nro_documento { get; set; }
        public string tipo_documento { get; set; }
        public System.DateTime fechaDeNacimiento { get; set; }
        public string mail { get; set; }
        public int telefono { get; set; }
        public bool estado { get; set; }
        public decimal creditoTotal { get; set; }
        public int id_domicilio { get; set; }
        public int id_usuario { get; set; }
    
        public virtual DOMICILIO DOMICILIO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<COMPRA> COMPRA { get; set; }
        public virtual ICollection<CREDITO> CREDITO { get; set; }
    }
}
