//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCuponFrbaT_REX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREDITO
    {
        public int id_credito { get; set; }
        public System.DateTime fecha_credito { get; set; }
        public int id_cliente { get; set; }
        public int id_forma_pago { get; set; }
        public decimal monto_credito { get; set; }
        public int id_tarjeta { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual FORMA_PAGO FORMA_PAGO { get; set; }
        public virtual TARJETA TARJETA { get; set; }
    }
}
